apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: https
      nodePort: 30007  # Choose a port number that is available in your cluster
  selector:
    app.kubernetes.io/name: argocd-server
